function renderAdminPanel(main) {
  if (!isAdmin(state.user)) { main.innerHTML = emptyHTML('🛡️', 'Доступ запрещён', 'Только администраторы.'); return; }
  const ru = state.users.filter(u => !u.id.startsWith('demo_') && u.username !== 'demo_user');
  const tu = ru.length, au = ru.filter(u => !isBanned(u)).length, bu = ru.filter(u => isBanned(u)).length, mu = ru.filter(u => isMuted(u) && !isBanned(u)).length;
  const tl = state.listings.length, pl = state.listings.filter(i => i.status === 'pending'), uc = state.complaints.filter(c => !c.resolved).length;
  const ot = (state.support || []).filter(t => t.status !== 'closed');
  main.innerHTML = `<div class="admin-panel"><div class="admin-header"><div class="admin-title">🛡️ Админ-панель</div><button class="btn btn-primary" id="generateCodeBtn">🔑 Сгенерировать код</button></div>
    <div class="admin-stats"><div class="admin-stat-card"><div class="admin-stat-value">${tu}</div><div class="admin-stat-label">👥 Всего пользователей</div></div><div class="admin-stat-card"><div class="admin-stat-value">${au}</div><div class="admin-stat-label">✅ Активных</div></div><div class="admin-stat-card"><div class="admin-stat-value" style="color:var(--danger);">${bu}</div><div class="admin-stat-label">🚫 Заблокировано</div></div><div class="admin-stat-card"><div class="admin-stat-value" style="color:var(--warning);">${mu}</div><div class="admin-stat-label">🔇 С ограничениями</div></div><div class="admin-stat-card"><div class="admin-stat-value">${tl}</div><div class="admin-stat-label">📦 Всего объявлений</div></div><div class="admin-stat-card"><div class="admin-stat-value" style="color:var(--warning);">${pl.length}</div><div class="admin-stat-label">⏳ На модерации</div></div><div class="admin-stat-card"><div class="admin-stat-value" style="color:var(--danger);">${uc}</div><div class="admin-stat-label">🚨 Жалоб</div></div><div class="admin-stat-card"><div class="admin-stat-value" style="color:var(--info);">${ot.length}</div><div class="admin-stat-label">🛠️ Тикетов</div></div></div>
    ${state.user.creatorCodeUsed ? `<div class="admin-section"><div class="admin-section-title">🚧 Технические работы (только создатель)</div><div class="user-item" style="flex-direction:column;align-items:stretch;gap:12px;"><div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;"><span style="font-weight:700;">Режим техработ:</span><span class="user-item-status ${state.maintenance ? 'status-banned' : 'status-active'}">${state.maintenance ? '🔴 ВКЛЮЧЕНЫ' : '🟢 ВЫКЛЮЧЕНЫ'}</span><button class="btn ${state.maintenance ? 'btn-success' : 'btn-danger'}" id="maintenanceToggle">${state.maintenance ? '✅ Выключить' : '🚫 Включить'}</button></div><div class="form-group" style="margin-bottom:0;"><label>Сообщение пользователям</label><textarea id="maintenanceMessage" rows="2" placeholder="Ведутся технические работы...">${escapeHtml(state.maintenanceMsg || '')}</textarea></div><button class="btn btn-primary" id="maintenanceSave" style="align-self:flex-start;">💾 Сохранить сообщение</button><div style="font-size:11px;color:var(--text-muted);">Пока техработы включены, все кроме создателя видят заглушку и не могут пользоваться маркетом.</div></div></div>` : ''}
    <div class="admin-section"><div class="admin-section-title">👥 Управление пользователями (${tu})</div>${ru.length === 0 ? '<div style="padding:20px;text-align:center;color:var(--text-muted);">Пока нет зарегистрированных пользователей</div>' : `<div class="user-list">${ru.map(u => { const r = getUserRating(u.username); return `<div class="user-item"><div class="user-item-header"><div class="user-item-avatar">${renderAvatarHTML(u)}</div><div class="user-item-info"><div class="user-item-name">${escapeHtml(u.name)} ${isAdmin(u) ? '<span style="color:var(--accent-light);font-size:10px;">🛡️</span>' : ''}</div><div class="user-item-user">@${escapeHtml(u.username)} ${r.count > 0 ? ` · ${renderStars(r.avg)} (${r.count})` : ''}</div></div><div class="user-item-status ${isBanned(u) ? 'status-banned' : isMuted(u) ? 'status-muted' : 'status-active'}">${isBanned(u) ? '🚫 Забанен' : isMuted(u) ? '🔇 Ограничен' : '✅ Активен'}</div></div><div class="user-item-actions">${!isBanned(u) && !isAdmin(u) ? `<button class="btn btn-danger" data-ban="${u.username}">🚫 Забанить</button>` : ''}${!isMuted(u) && !isBanned(u) && !isAdmin(u) ? `<button class="btn btn-warning" data-mute="${u.username}">🔇 Мут</button>` : ''}${(isBanned(u) || isMuted(u)) && !isAdmin(u) ? `<button class="btn btn-success" data-unban="${u.username}">✅ Разбанить</button>` : ''}<button class="btn btn-info" data-info="${u.username}">ℹ️ Инфо</button></div></div>`; }).join('')}</div>`}</div>
    <div class="admin-section"><div class="admin-section-title">⏳ Модерация объявлений (${pl.length})</div>${pl.length === 0 ? '<div style="padding:20px;text-align:center;color:var(--text-muted);">✅ Нет объявлений на модерации</div>' : `<div class="user-list">${pl.map(i => `<div class="user-item"><div class="user-item-header"><div style="width:60px;height:60px;border-radius:8px;background:linear-gradient(135deg,#1a3d2a,#0d2818);display:flex;align-items:center;justify-content:center;font-size:30px;">${i.img ? `<img src="${i.img}" style="width:100%;height:100%;object-fit:cover;border-radius:8px;">` : (CAT_ICONS[i.category] || '📦')}</div><div class="user-item-info"><div class="user-item-name">${escapeHtml(i.title)}</div><div class="user-item-user">${formatPrice(i.price)} · @${escapeHtml(i.seller.username)} · ${timeAgo(i.date)}</div></div></div><div class="user-item-actions"><button class="btn btn-success" data-approve="${i.id}">✅ Одобрить</button><button class="btn btn-danger" data-reject="${i.id}">❌ Отклонить</button></div></div>`).join('')}</div>`}</div>
    <div class="admin-section"><div class="admin-section-title">🚨 Жалобы (${uc} нерешённых)</div>${state.complaints.length === 0 ? '<div style="padding:20px;text-align:center;color:var(--text-muted);">Жалоб нет</div>' : `<div class="user-list">${state.complaints.map(c => `<div class="user-item"><div style="flex:1;"><div style="font-weight:700;">${escapeHtml(c.reason)} · @${escapeHtml(c.reporter)} → @${escapeHtml(c.target)}</div><div style="font-size:10px;color:var(--text-muted);margin-top:4px;">${timeAgo(c.time)} ${c.resolved ? '· ✅ Решено' : ''}</div><div style="margin-top:6px;font-size:12px;">${escapeHtml(c.description)}</div></div>${!c.resolved ? `<div style="margin-top:8px;display:flex;gap:8px;"><button class="btn btn-success" data-resolve-complaint="${c.id}">✅ Решено</button><button class="btn btn-danger" data-ban-complaint="${c.target}">🚫 Забанить</button></div>` : ''}</div>`).join('')}</div>`}</div>
    <div class="admin-section"><div class="admin-section-title">🛠️ Техподдержка (${ot.length} открытых / ${(state.support || []).length} всего)</div>${(state.support || []).length === 0 ? '<div style="padding:20px;text-align:center;color:var(--text-muted);">Нет обращений</div>' : `<div class="user-list">${(state.support || []).map(t => renderSupportTicketAdmin(t)).join('')}</div>`}</div>
  </div>`;
  document.getElementById('generateCodeBtn').addEventListener('click', () => { const code = generateAdminCode(); db.ref('adminCodes').push({ code, used: false, createdAt: Date.now() }); document.getElementById('codeText').textContent = code; openModal('adminCodeModal'); document.getElementById('copyCodeBtn').onclick = () => { navigator.clipboard.writeText(code).then(() => toast('✅ Код скопирован', 'success')); }; });
  main.querySelectorAll('[data-ban]').forEach(b => b.addEventListener('click', () => openActionModal(b.dataset.ban, 'ban')));
  main.querySelectorAll('[data-mute]').forEach(b => b.addEventListener('click', () => openActionModal(b.dataset.mute, 'mute')));
  main.querySelectorAll('[data-unban]').forEach(b => b.addEventListener('click', () => openActionModal(b.dataset.unban, 'unban')));
  main.querySelectorAll('[data-info]').forEach(b => b.addEventListener('click', () => showUserInfo(b.dataset.info)));
  main.querySelectorAll('[data-approve]').forEach(b => b.addEventListener('click', () => { db.ref('listings/' + b.dataset.approve).update({ status: 'approved', rejectReason: null }); toast('✅ Одобрено', 'success'); }));
  main.querySelectorAll('[data-reject]').forEach(b => b.addEventListener('click', () => { const r = prompt('Причина отклонения:'); if (r) { db.ref('listings/' + b.dataset.reject).update({ status: 'rejected', rejectReason: r }); toast('❌ Отклонено', 'warning'); } }));
  main.querySelectorAll('[data-resolve-complaint]').forEach(b => b.addEventListener('click', () => { db.ref('complaints/' + b.dataset.resolveComplaint).update({ resolved: true, resolvedAt: Date.now() }); toast('✅ Жалоба решена', 'success'); }));
  main.querySelectorAll('[data-ban-complaint]').forEach(b => b.addEventListener('click', () => openActionModal(b.dataset.banComplaint, 'ban')));
  main.querySelectorAll('[data-open-ticket]').forEach(b => b.addEventListener('click', () => openSupportTicketAdmin(b.dataset.openTicket)));
  main.querySelectorAll('[data-progress-ticket]').forEach(b => b.addEventListener('click', () => { db.ref('support/' + b.dataset.progressTicket).update({ status: 'in_progress', updatedAt: Date.now() }); toast('🟡 Тикет взят в работу', 'success'); }));
  main.querySelectorAll('[data-close-ticket]').forEach(b => b.addEventListener('click', () => { if (confirm('✅ Закрыть этот тикет?')) { db.ref('support/' + b.dataset.closeTicket).update({ status: 'closed', updatedAt: Date.now() }); toast('✅ Тикет закрыт', 'success'); } }));
  main.querySelectorAll('[data-reopen-ticket]').forEach(b => b.addEventListener('click', () => { db.ref('support/' + b.dataset.reopenTicket).update({ status: 'open', updatedAt: Date.now() }); toast('🔓 Тикет снова открыт', 'success'); }));
  main.querySelectorAll('[data-delete-ticket]').forEach(b => b.addEventListener('click', () => { if (confirm('🗑️ Удалить тикет безвозвратно?')) { db.ref('support/' + b.dataset.deleteTicket).remove(); toast('🗑️ Тикет удалён', 'warning'); } }));
  const mt = document.getElementById('maintenanceToggle');
  if (mt) mt.addEventListener('click', () => { const on = !state.maintenance; if (on && !confirm('Включить технические работы для всех, кроме тебя?')) return; db.ref('settings/maintenance').update({ enabled: on, message: state.maintenanceMsg || 'Ведутся технические работы.' }); toast(on ? '🚧 Техработы включены' : '✅ Техработы выключены', on ? 'warning' : 'success'); });
  const ms = document.getElementById('maintenanceSave');
  if (ms) ms.addEventListener('click', () => { const tx = (document.getElementById('maintenanceMessage').value || '').trim() || 'Ведутся технические работы.'; db.ref('settings/maintenance').update({ message: tx, enabled: state.maintenance }); toast('💾 Сообщение сохранено', 'success'); });
}
function renderSupportTicketAdmin(t) {
  const u = state.users.find(x => x.id === t.userId) || { name: t.name, username: t.username };
  const sc = t.status === 'closed' ? 'status-closed' : (t.status === 'in_progress' ? 'status-progress' : 'status-open');
  const st = { open: '🟢 Открыт', in_progress: '🟡 В работе', closed: '⚫ Закрыт' }[t.status] || '🟢 Открыт';
  const lm = t.messages && t.messages.length ? t.messages[t.messages.length - 1] : null;
  const ur = t.messages ? t.messages.filter(m => m.isAdmin === false && !m.read).length : 0;
  return `<div class="user-item"><div class="user-item-header"><div class="user-item-avatar">${renderAvatarHTML(u)}</div><div class="user-item-info"><div class="user-item-name">${escapeHtml(t.subject || 'Обращение #' + t.id.slice(-5))}${ur > 0 ? `<span style="color:var(--danger);font-size:11px;margin-left:8px;">🔔 ${ur} новых</span>` : ''}</div><div class="user-item-user">@${escapeHtml(t.username)} · ${escapeHtml(t.name)} · ${timeAgo(t.createdAt)}</div></div><div class="user-item-status ${sc}">${st}</div></div>${lm ? `<div style="font-size:12px;color:var(--text-muted);padding:8px 0 0 56px;">💬 ${escapeHtml(lm.text || '(вложение)').slice(0, 80)}</div>` : ''}<div class="user-item-actions"><button class="btn btn-info" data-open-ticket="${t.id}">💬 Открыть</button>${t.status !== 'closed' ? `<button class="btn btn-warning" data-progress-ticket="${t.id}">🟡 В работу</button>` : ''}${t.status !== 'closed' ? `<button class="btn btn-success" data-close-ticket="${t.id}">✅ Закрыть</button>` : `<button class="btn" data-reopen-ticket="${t.id}">🔓 Открыть снова</button>`}<button class="btn btn-danger" data-delete-ticket="${t.id}">🗑️ Удалить</button></div></div>`;
}
function openSupportTicketAdmin(tid) {
  const t = (state.support || []).find(x => x.id === tid); if (!t) return;
  const up = {}; if (t.messages) t.messages.forEach((m, i) => { if (!m.isAdmin && !m.read) up['support/' + t.id + '/messages/' + i + '/read'] = true; });
  if (Object.keys(up).length) db.ref().update(up);
  const ov = document.createElement('div'); ov.className = 'modal-overlay active'; ov.style.cssText = 'z-index:4000;';
  ov.innerHTML = `<div class="modal" style="max-width:640px;max-height:90vh;display:flex;flex-direction:column;"><div class="modal-header"><h2>🛠️ ${escapeHtml(t.subject || 'Тикет #' + t.id.slice(-5))}</h2><button class="modal-close" data-close-ticket-modal>×</button></div><div style="padding:10px 20px;background:rgba(10,26,15,0.4);border-bottom:1px solid var(--border);font-size:12px;color:var(--text-muted);">👤 ${escapeHtml(t.name)} (@${escapeHtml(t.username)}) · 📅 ${timeAgo(t.createdAt)}</div><div class="modal-body" id="adminTicketMessages" style="flex:1;overflow-y:auto;max-height:50vh;display:flex;flex-direction:column;gap:10px;">${(t.messages || []).map((m, i) => renderSupportMessage(m, i)).join('') || '<div style="text-align:center;color:var(--text-muted);padding:20px;">Нет сообщений</div>'}</div>${t.status !== 'closed' ? `<div style="padding:12px 20px;border-top:1px solid var(--border);"><div id="adminSupportAttachments" style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px;"></div><div style="display:flex;gap:8px;"><button class="btn" id="adminSupportAttachBtn">📎</button><input type="text" id="adminSupportMsgInput" placeholder="Ответить пользователю..." style="flex:1;padding:10px;background:rgba(10,26,15,0.6);border:1px solid var(--border);border-radius:10px;color:var(--text);font-size:13px;"><button class="btn btn-primary" id="adminSupportSendBtn">➤</button></div><input type="file" id="adminSupportFileInput" accept="image/*" multiple style="display:none;"></div>` : '<div style="padding:12px 20px;text-align:center;color:var(--text-muted);border-top:1px solid var(--border);">⚫ Тикет закрыт</div>'}</div>`;
  document.body.appendChild(ov);
  setTimeout(() => { const mm = document.getElementById('adminTicketMessages'); if (mm) mm.scrollTop = mm.scrollHeight; }, 100);
  const cl = () => ov.remove();
  ov.querySelector('[data-close-ticket-modal]').addEventListener('click', cl);
  ov.addEventListener('click', (e) => { if (e.target === ov) cl(); });
  if (t.status !== 'closed') {
    let aa = []; const ab = ov.querySelector('#adminSupportAttachBtn'), fi = ov.querySelector('#adminSupportFileInput'), sb = ov.querySelector('#adminSupportSendBtn'), mi = ov.querySelector('#adminSupportMsgInput'), bx = ov.querySelector('#adminSupportAttachments');
    const raa = () => { bx.innerHTML = aa.map((a, i) => `<div style="position:relative;display:inline-block;"><img src="${a.url}" style="width:50px;height:50px;object-fit:cover;border-radius:6px;border:1px solid var(--border);"><button type="button" data-rm="${i}" style="position:absolute;top:-6px;right:-6px;width:18px;height:18px;border-radius:50%;background:var(--danger);color:white;border:none;font-size:10px;cursor:pointer;padding:0;">✕</button></div>`).join(''); bx.querySelectorAll('[data-rm]').forEach(b => b.addEventListener('click', () => { aa.splice(parseInt(b.dataset.rm), 1); raa(); })); };
    ab.addEventListener('click', () => fi.click());
    fi.addEventListener('change', async (e) => { for (const f of Array.from(e.target.files)) { if (!f.type.startsWith('image/')) continue; if (f.size > 5 * 1024 * 1024) { toast('⚠️ Файл слишком большой', 'warning'); continue; } try { const r = new FileReader(); r.onload = (ev) => { aa.push({ url: ev.target.result, name: f.name }); raa(); }; r.readAsDataURL(f); } catch (er) { toast('❌ Ошибка загрузки', 'error'); } } fi.value = ''; });
    const send = async () => { const tx = mi.value.trim(); if (!tx && !aa.length) return; const nm = { from: state.user.username, fromId: state.user.id, text: tx, attachments: aa.slice(), time: Date.now(), read: false, isAdmin: true }; try { await db.ref('support/' + t.id + '/messages').push(nm); await db.ref('support/' + t.id).update({ updatedAt: Date.now(), status: 'in_progress' }); mi.value = ''; aa = []; raa(); db.ref('notifications/' + t.userId).push({ title: '🛠️ Ответ от поддержки', message: `По вашему обращению "${t.subject || '#' + t.id.slice(-5)}" получен ответ.`, type: 'info', time: Date.now(), read: false }); const ut = (state.support || []).find(x => x.id === tid); document.getElementById('adminTicketMessages').innerHTML = (ut.messages || []).map((m, i) => renderSupportMessage(m, i)).join(''); setTimeout(() => { const mm = document.getElementById('adminTicketMessages'); if (mm) mm.scrollTop = mm.scrollHeight; }, 100); } catch (er) { toast('❌ Ошибка отправки', 'error'); } };
    sb.addEventListener('click', send); mi.addEventListener('keydown', e => { if (e.key === 'Enter') send(); });
  }
}
function openActionModal(un, at) {
  document.getElementById('targetUsername').value = un; document.getElementById('actionType').value = at;
  document.getElementById('actionModalTitle').textContent = at === 'ban' ? '🚫 Забанить' : at === 'mute' ? '🔇 Ограничить' : '✅ Разбанить';
  document.getElementById('durationGroup').style.display = at === 'mute' ? 'block' : 'none';
  document.getElementById('actionSubmitBtn').className = at === 'unban' ? 'btn btn-success' : 'btn btn-danger';
  openModal('actionModal');
}
function showUserInfo(un) {
  const u = state.users.find(x => x.username === un) || { name: un, username: un };
  const ul = state.listings.filter(i => i.seller.username === un); const uch = state.chats.filter(c => c.participants && c.participants.includes(un));
  const r = getUserRating(un); const uco = state.complaints.filter(c => c.target === un); const ut = (state.support || []).filter(x => x.username === un);
  alert(`👤 ${u.name} (@${u.username})\n\n📊 Объявлений: ${ul.length}\n💬 Чатов: ${uch.length}\n⭐ Рейтинг: ${r.avg.toFixed(1)} (${r.count} отзывов)\n🚨 Жалоб: ${uco.length}\n🛠️ Тикетов: ${ut.length}\n\nСтатус: ${isBanned(u) ? '🚫 Заблокирован' : isMuted(u) ? '🔇 Ограничен' : '✅ Активен'}`);
}
document.getElementById('actionForm').addEventListener('submit', (e) => {
  e.preventDefault(); const fd = Object.fromEntries(new FormData(e.target));
  const u = state.users.find(x => x.username === fd.targetUsername); if (!u) { toast('❌ Пользователь не найден', 'error'); return; }
  const up = {};
  if (fd.actionType === 'ban') { up.banned = true; up.banReason = fd.reason; up.banBy = state.user.username; up.bannedAt = Date.now(); if (fd.duration) up.banUntil = Date.now() + parseInt(fd.duration) * 3600000; toast(`🚫 @${u.username} заблокирован`, 'warning'); }
  else if (fd.actionType === 'mute') { up.muted = true; up.muteReason = fd.reason; up.muteBy = state.user.username; up.mutedAt = Date.now(); if (fd.duration) up.muteUntil = Date.now() + parseInt(fd.duration) * 3600000; toast(`🔇 @${u.username} ограничен`, 'warning'); }
  else { up.banned = false; up.muted = false; up.banUntil = null; up.muteUntil = null; toast(`✅ @${u.username} разблокирован`, 'success'); }
  db.ref('users/' + u.id).update(up); closeModal(e.target.closest('.modal-overlay'));
});
document.getElementById('actionType').addEventListener('change', (e) => { document.getElementById('durationGroup').style.display = e.target.value === 'mute' ? 'block' : 'none'; });